spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    sql-script-encoding: UTF-8
    continue-on-error: true